backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "public/resources/main/uploads"
public_folder: "/resources/main/uploads"
collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Products" # Used in the UI
    folder: "src/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{product_name}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Name", name: "product_name", widget: "string" }
      - { label: "Identifier", name: "tags", widget: "string" }
      - { label: "Prize", name: "product_prize", widget: "string" }
      - { label: "Description", name: "product_description", widget: "string" }
      - { label: "Shop Link", name: "product_shop_link", widget: "string" }
      - { label: "Review", name: "product_review_score", widget: "string" }
      - { label: "Image", name: "product_image", widget: "image" }
      - {
          label: "Image Alternative",
          name: "product_image_alternative_text",
          widget: "string",
        }

  - name: "about" # Used in routes, e.g., /admin/collections/blog
    label: "About" # Used in the UI
    folder: "src/command/about" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{product_name}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "About", name: "name", widget: "string" }
      - {
          label: "First Article Name",
          name: "first_article_name",
          widget: "string",
        }
      - {
          label: "First Article Description",
          name: "first_article_description",
          widget: "string",
        }
      - {
          label: "Second Article Name",
          name: "second_article_name",
          widget: "string",
        }
      - {
          label: "Second Article Desription",
          name: "second_article_description",
          widget: "string",
        }
      - {
          label: "Third Article Name",
          name: "third_article_name",
          widget: "string",
        }
      - {
          label: "Third Article Description",
          name: "third_article_description",
          widget: "string",
        }
      - {
          label: "Fourth Article Name",
          name: "fourth_article_name",
          widget: "string",
        }
      - {
          label: "Fourth Article Desription",
          name: "fourth_article_description",
          widget: "string",
        }
